"use client";

import Link from "next/link";
import { CalendarDays, Check, ChevronRight, Clock3, Dumbbell, GripVertical, Plus } from "lucide-react";
import { workoutExercises } from "@/mock/data";
import { Badge, PageIntro, SectionHeader } from "@/components/ui";

export default function PlanPage() { return <><PageIntro eyebrow="Weekly rhythm" title="训练计划" subtitle="PPL + Core V1 · 让每一次训练都有方向。" action={<Link href="/history" className="secondary-button px-3"><CalendarDays size={18} />历史</Link>} /><div className="app-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5"><div><div className="eyebrow">Current plan</div><h2 className="mt-1 text-xl font-bold">PPL + Core V1</h2></div><button className="secondary-button min-h-10 px-3 text-sm"><Plus size={16} />编辑</button></div><div className="grid grid-cols-5 gap-2 p-4">{["Push", "Pull", "Legs", "Core", "Rest"].map((item, index) => <div key={item} className={`rounded-2xl p-3 text-center ${index === 0 ? "bg-blue-600 text-white" : "bg-slate-50 text-slate-500"}`}><div className="text-xs font-semibold">DAY {index + 1}</div><div className="mt-1 text-sm font-bold">{item}</div></div>)}</div></div><div className="mt-6"><SectionHeader title="今天 · PUSH" action={<Badge tone="purple">6 个动作</Badge>} /><div className="app-card divide-y divide-slate-100 overflow-hidden">{workoutExercises.map((exercise, index) => <Link href={`/workout/push-2026-08-17?exercise=${exercise.id}`} key={exercise.id} className="flex items-center gap-3 p-4 transition hover:bg-blue-50/50"><GripVertical size={16} className="text-slate-300" /><div className={`flex h-10 w-10 items-center justify-center rounded-2xl ${exercise.color === "purple" ? "bg-violet-50 text-violet-600" : exercise.color === "green" ? "bg-emerald-50 text-emerald-500" : "bg-blue-50 text-blue-600"}`}><Dumbbell size={19} /></div><div className="min-w-0 flex-1"><div className="font-semibold">{exercise.name}</div><div className="mt-1 text-xs text-slate-400">{exercise.focus} · 休息 {exercise.rest} 秒</div></div><div className="text-right"><div className="font-semibold text-blue-600">{exercise.sets} × {exercise.reps}</div><ChevronRight size={17} className="ml-auto mt-1 text-slate-300" /></div></Link>)}</div></div><div className="app-card mt-4 p-5"><div className="flex items-center gap-3"><div className="icon-tile bg-blue-50 text-blue-600"><Clock3 size={20} /></div><div><div className="font-semibold">训练小提示</div><div className="mt-1 text-sm text-slate-500">先完成热身，再从第一个正式组开始记录。</div></div></div><Link href="/workout/push-2026-08-17" className="primary-button mt-5 w-full"><Dumbbell size={18} />开始 PUSH 训练</Link></div><div className="mt-6"><SectionHeader title="计划原则" /><div className="grid gap-3 sm:grid-cols-3"><Info title="保持顺序" text="动作顺序影响今天的发力状态。" icon={<GripVertical size={18} />} /><Info title="记录每组" text="重量、次数与 RIR 都会成为下一次提示。" icon={<Check size={18} />} /><Info title="只影响未来" text="修改计划不会改变历史训练快照。" icon={<Clock3 size={18} />} /></div></div></> }
function Info({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <div className="app-card p-4"><div className="icon-tile h-9 w-9 bg-blue-50 text-blue-600">{icon}</div><div className="mt-3 font-semibold">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{text}</div></div>; }
