import type { ExerciseLibraryRow, WorkoutPlanGraph, WorkoutSessionGraph, WorkoutSetRow } from "@/lib/db/repositories";
import type { ExerciseLibraryRecord, WorkoutPlanRecord, WorkoutSessionRecord, WorkoutSetRecord } from "@/types";
import { postWithOfflineFallback } from "@/lib/offline/sync";

async function request<T>(input: RequestInfo | URL, init?: RequestInit): Promise<T> {
  const response = await fetch(input, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const payload = (await response.json().catch(() => ({}))) as { error?: string } & T;
  if (!response.ok) throw new Error(payload.error ?? `Request failed with status ${response.status}`);
  return payload;
}

function mapExercise(row: ExerciseLibraryRow): ExerciseLibraryRecord { return { id: row.id, name: row.name, category: row.category, primaryMuscle: row.primary_muscle, equipment: row.equipment, defaultRestSeconds: row.default_rest_seconds === null ? null : Number(row.default_rest_seconds), isActive: row.is_active }; }
function mapPlan(graph: WorkoutPlanGraph): WorkoutPlanRecord { return { id: graph.plan.id, name: graph.plan.name, version: graph.plan.version, description: graph.plan.description, days: graph.days.map(({ day, exercises }) => ({ id: day.id, dayCode: day.day_code, name: day.name, sortOrder: day.sort_order, estimatedMinutes: day.estimated_minutes === null ? null : Number(day.estimated_minutes), isRestDay: day.is_rest_day, exercises: exercises.map(({ planExercise, exercise }) => ({ id: planExercise.id, exerciseId: planExercise.exercise_id, exercise: mapExercise(exercise), sortOrder: planExercise.sort_order, targetSets: planExercise.target_sets, repMin: planExercise.rep_min, repMax: planExercise.rep_max, targetRir: planExercise.target_rir === null ? null : Number(planExercise.target_rir), restSeconds: planExercise.rest_seconds, isOptional: planExercise.is_optional })) })) }; }
function mapSet(row: WorkoutSetRow): WorkoutSetRecord { return { id: row.id, sessionExerciseId: row.session_exercise_id, setNumber: row.set_number, setType: row.set_type, weightKg: row.weight_kg === null ? null : Number(row.weight_kg), reps: row.reps === null ? null : Number(row.reps), rir: row.rir === null ? null : Number(row.rir), durationSeconds: row.duration_seconds === null ? null : Number(row.duration_seconds), completedAt: row.completed_at, isCompleted: row.is_completed }; }
function mapSession(graph: WorkoutSessionGraph): WorkoutSessionRecord { return { id: graph.session.id, recordDate: graph.session.record_date, planId: graph.session.plan_id, planDayId: graph.session.plan_day_id, workoutTypeSnapshot: graph.session.workout_type_snapshot, workoutNameSnapshot: graph.session.workout_name_snapshot, startedAt: graph.session.started_at, endedAt: graph.session.ended_at, durationMinutes: graph.session.duration_minutes === null ? null : Number(graph.session.duration_minutes), feelingScore: graph.session.feeling_score, note: graph.session.note, status: graph.session.status, exercises: graph.exercises.map(({ exercise, sets }) => ({ id: exercise.id, sessionId: exercise.session_id, exerciseId: exercise.exercise_id, exerciseNameSnapshot: exercise.exercise_name_snapshot, sortOrder: exercise.sort_order, targetSetsSnapshot: exercise.target_sets_snapshot, repMinSnapshot: exercise.rep_min_snapshot, repMaxSnapshot: exercise.rep_max_snapshot, targetRirSnapshot: exercise.target_rir_snapshot === null ? null : Number(exercise.target_rir_snapshot), restSecondsSnapshot: exercise.rest_seconds_snapshot, status: exercise.status, sets: sets.map(mapSet) })), summary: graph.summary ? { workingSets: Number(graph.summary.working_sets), totalReps: Number(graph.summary.total_reps), totalVolumeKg: Number(graph.summary.total_volume_kg) } : null }; }

export async function getWorkoutPlans(): Promise<WorkoutPlanRecord[]> { const rows = await request<WorkoutPlanGraph[]>("/api/workout/plans", { cache: "no-store" }); return rows.map(mapPlan); }
export async function startWorkout(input: { recordDate: string; planId: string; planDayId: string }): Promise<WorkoutSessionRecord> { const row = await request<WorkoutSessionGraph>("/api/workout/sessions", { method: "POST", body: JSON.stringify({ ...input, clientIdempotencyKey: crypto.randomUUID() }) }); return mapSession(row); }
export async function getWorkoutSession(id: string): Promise<WorkoutSessionRecord> { return mapSession(await request<WorkoutSessionGraph>(`/api/workout/sessions/${id}`, { cache: "no-store" })); }
export async function recordWorkoutSet(sessionId: string, input: { sessionExerciseId: string; setNumber: number; setType: WorkoutSetRecord["setType"]; weightKg: number | null; reps: number | null; rir: number | null; durationSeconds?: number | null; isCompleted?: boolean }): Promise<WorkoutSetRecord | null> { const clientIdempotencyKey = crypto.randomUUID(); const row = await postWithOfflineFallback<WorkoutSetRow>(`/api/workout/sessions/${sessionId}/sets`, { ...input, isCompleted: input.isCompleted ?? true, clientIdempotencyKey }, clientIdempotencyKey); return row ? mapSet(row) : null; }
export async function finishWorkout(id: string, input: { feelingScore: number | null; note: string | null; durationMinutes?: number | null }): Promise<WorkoutSessionRecord> { return mapSession(await request<WorkoutSessionGraph>(`/api/workout/sessions/${id}`, { method: "PATCH", body: JSON.stringify(input) })); }
export async function getLastWorkoutSet(exerciseId: string, sessionId?: string): Promise<{ date: string; set: WorkoutSetRecord } | null> { const row = await request<{ date: string; set: WorkoutSetRow } | null>(`/api/workout/history?exerciseId=${encodeURIComponent(exerciseId)}${sessionId ? `&sessionId=${encodeURIComponent(sessionId)}` : ""}`, { cache: "no-store" }); return row ? { date: row.date, set: mapSet(row.set) } : null; }
export async function getWorkoutSessions(date: string): Promise<WorkoutSessionRecord[]> { const rows = await request<WorkoutSessionGraph[]>(`/api/workout/sessions?date=${encodeURIComponent(date)}`, { cache: "no-store" }); return rows.map(mapSession); }
