"use client";
/* eslint-disable @next/next/no-img-element */

import { Camera, ImagePlus, Loader2, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { listMedia, removeMedia, uploadMedia, type MediaAsset, type MediaEntityType } from "@/services/media-service";

export function MediaUploader({ entityType, entityId, role, title = "添加图片" }: { entityType: MediaEntityType; entityId: string; role: string; title?: string }) {
  const cameraRef = useRef<HTMLInputElement>(null); const galleryRef = useRef<HTMLInputElement>(null);
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; void listMedia(entityType, entityId).then(items => { if (active) setAssets(items); }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : "图片加载失败"); }); return () => { active = false; }; }, [entityId, entityType]);
  async function onFiles(files: FileList | null) { if (!files?.length) return; setBusy(true); setError(""); try { const added: MediaAsset[] = []; for (const file of Array.from(files)) added.push(await uploadMedia({ file, entityType, entityId, role })); setAssets(current => [...added, ...current]); } catch (reason) { setError(reason instanceof Error ? reason.message : "图片上传失败"); } finally { setBusy(false); } }
  async function remove(asset: MediaAsset) { setBusy(true); try { await removeMedia(asset.id); setAssets(current => current.filter(item => item.id !== asset.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "图片删除失败"); } finally { setBusy(false); } }
  return <div className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div className="text-sm font-semibold text-slate-700">{title}</div><div className="flex gap-2"><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={event => void onFiles(event.target.files)} /><input ref={galleryRef} className="hidden" type="file" accept="image/*" multiple onChange={event => void onFiles(event.target.files)} /><button type="button" className="secondary-button h-9 px-3 text-xs" disabled={busy} onClick={() => cameraRef.current?.click()}><Camera size={15} />拍照</button><button type="button" className="secondary-button h-9 px-3 text-xs" disabled={busy} onClick={() => galleryRef.current?.click()}><ImagePlus size={15} />相册</button></div></div>{busy && <div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Loader2 size={14} className="animate-spin" />处理中…</div>}{error && <p className="mt-2 text-xs text-red-600">{error}</p>}{assets.length > 0 && <div className="mt-3 grid grid-cols-3 gap-2">{assets.map(asset => <div key={asset.id} className="group relative overflow-hidden rounded-xl bg-white">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={asset.signedUrl} alt={asset.original_filename ?? "记录图片"} className="aspect-square w-full object-cover" /><button type="button" aria-label="删除图片" className="absolute right-1 top-1 rounded-lg bg-black/55 p-1.5 text-white opacity-0 transition group-hover:opacity-100" onClick={() => void remove(asset)}><Trash2 size={13} /></button></div>)}</div>}</div>;
}
