"use client";

import Link from "next/link";
import { Activity, BriefcaseBusiness, Camera, Dumbbell, Droplets, NotebookPen, Scale, Utensils, Wallet } from "lucide-react";
import { useState } from "react";
import { useAppState } from "@/components/app-state";
import { Sheet } from "@/components/ui";

type ActionKey = "water" | "expense" | "body";
const actions = [{ key: "meal", title: "饮食", icon: Utensils, tone: "green" }, { key: "water", title: "饮水", icon: Droplets, tone: "blue" }, { key: "workout", title: "训练", icon: Dumbbell, tone: "purple" }, { key: "expense", title: "支出", icon: Wallet, tone: "orange" }, { key: "body", title: "体重", icon: Scale, tone: "blue" }, { key: "work", title: "工作", icon: BriefcaseBusiness, tone: "green" }, { key: "cardio", title: "有氧", icon: Activity, tone: "green" }, { key: "note", title: "随手记", icon: NotebookPen, tone: "purple" }, { key: "photo", title: "图片", icon: Camera, tone: "orange" }] as const;

export function QuickAddSheet({ open, onClose }: { open: boolean; onClose: () => void }) { const [active, setActive] = useState<ActionKey | null>(null); const { addWater, addExpense, addBody } = useAppState(); const saveWater = (amount: number) => { addWater(amount); onClose(); setActive(null); }; return <Sheet open={open} title={active ? ({ water: "记录饮水", expense: "记录支出", body: "记录晨重" }[active]) : "快速记录"} subtitle={active ? "默认记录到今天" : "选择要记录的类型，快速添加"} onClose={() => { setActive(null); onClose(); }}>{active === null ? <div className="grid grid-cols-3 gap-3">{actions.map(({ key, title, icon: Icon, tone }) => <button key={key} onClick={() => { if (key === "meal") { window.location.href = "/nutrition/add"; return; } if (key === "workout") { window.location.href = "/workout/push-2026-08-17"; return; } if (key === "photo" || key === "work" || key === "cardio" || key === "note") { onClose(); return; } if (key === "water" || key === "expense" || key === "body") setActive(key); }} className="flex aspect-square flex-col items-center justify-center gap-3 rounded-2xl border border-slate-200 bg-white transition hover:border-blue-300 hover:bg-blue-50"><span className={`flex h-12 w-12 items-center justify-center rounded-full ${tone === "green" ? "bg-emerald-50 text-emerald-500" : tone === "purple" ? "bg-violet-50 text-violet-500" : tone === "orange" ? "bg-orange-50 text-orange-500" : "bg-blue-50 text-blue-600"}`}><Icon size={24} /></span><span className="font-semibold">{title}</span></button>)}</div> : active === "water" ? <WaterForm onSave={saveWater} /> : active === "expense" ? <ExpenseForm onSave={expense => { addExpense(expense); onClose(); setActive(null); }} /> : <BodyForm onSave={body => { addBody(body); onClose(); setActive(null); }} />}</Sheet>; }

function WaterForm({ onSave }: { onSave: (amount: number) => void }) { const { water } = useAppState(); const [custom, setCustom] = useState(""); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">今天已喝</div><div className="mt-1 text-3xl font-bold text-blue-600">{water} <span className="text-sm font-medium text-slate-500">/ 2500 ml</span></div></div><div className="grid grid-cols-3 gap-3">{[200, 300, 500].map(amount => <button key={amount} onClick={() => onSave(amount)} className="secondary-button px-2">+{amount} ml</button>)}</div><div className="mt-5 flex gap-3"><input className="field" type="number" placeholder="自定义 ml" value={custom} onChange={event => setCustom(event.target.value)} /><button className="primary-button" onClick={() => onSave(Number(custom) || 300)}>添加</button></div></div>; }
function ExpenseForm({ onSave }: { onSave: (expense: { amount: number; category: string; note: string }) => void }) { const [amount, setAmount] = useState("28"); const [category, setCategory] = useState("餐饮"); const [note, setNote] = useState(""); return <div><label className="muted">金额</label><div className="mt-2 flex items-center gap-2"><span className="text-3xl font-bold">¥</span><input className="field text-2xl font-bold" value={amount} onChange={e => setAmount(e.target.value)} /></div><div className="mt-5 grid grid-cols-4 gap-2">{["餐饮", "交通", "购物", "娱乐", "健身", "学习", "其他"].map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-2 py-3 text-sm ${category === item ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item}</button>)}</div><input className="field mt-5" placeholder="备注（可选）" value={note} onChange={e => setNote(e.target.value)} /><button className="primary-button mt-5 w-full" onClick={() => onSave({ amount: Number(amount) || 0, category, note })}>保存 ¥{amount || 0}</button></div>; }
function BodyForm({ onSave }: { onSave: (body: { weight: number; time: string }) => void }) { const [weight, setWeight] = useState("60.0"); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">晨重</div><div className="mt-1 flex items-baseline justify-center gap-2"><input className="w-36 bg-transparent text-center text-5xl font-bold text-blue-600 outline-none" value={weight} onChange={e => setWeight(e.target.value)} /><span className="text-slate-500">kg</span></div></div><label className="muted">测量时间</label><input className="field mt-2" type="time" defaultValue="07:05" /><button className="primary-button mt-5 w-full" onClick={() => onSave({ weight: Number(weight) || 0, time: "07:05" })}>保存晨重</button></div>; }
