"use client";

import { Activity, BriefcaseBusiness, Camera, Dumbbell, Droplets, NotebookPen, Scale, Utensils, Wallet } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAppState } from "@/components/app-state";
import { addCardio, addWork, currentRecordDate, getExpenseCategories } from "@/services/backend-service";
import { Sheet } from "@/components/ui";

type ActionKey = "water" | "expense" | "body" | "note" | "work" | "cardio";
const actions = [{ key: "meal", title: "饮食", icon: Utensils, tone: "green" }, { key: "water", title: "饮水", icon: Droplets, tone: "blue" }, { key: "workout", title: "训练", icon: Dumbbell, tone: "purple" }, { key: "expense", title: "支出", icon: Wallet, tone: "orange" }, { key: "body", title: "体重", icon: Scale, tone: "blue" }, { key: "work", title: "工作", icon: BriefcaseBusiness, tone: "green" }, { key: "cardio", title: "有氧", icon: Activity, tone: "green" }, { key: "note", title: "随手记", icon: NotebookPen, tone: "purple" }] as const;

export function QuickAddSheet({ open, onClose }: { open: boolean; onClose: () => void }) {
  const router = useRouter();
  const [active, setActive] = useState<ActionKey | null>(null);
  const [error, setError] = useState("");
  const { water, addWater, addExpense, addBody, addNote } = useAppState();
  const close = () => { setActive(null); setError(""); onClose(); };
  const run = async (operation: () => Promise<void>) => { try { setError(""); await operation(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败，请重试"); } };
  return <Sheet open={open} title={active ? ({ water: "记录饮水", expense: "记录支出", body: "记录晨重", note: "随手记", work: "记录工作", cardio: "记录有氧" }[active]) : "快速记录"} subtitle={active ? "默认记录到今天" : "选择要记录的类型，快速添加"} onClose={close}>
    {error && <p className="mb-4 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>}
    {active === null ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{actions.map(({ key, title, icon: Icon, tone }) => <button key={key} onClick={() => { if (key === "meal") { close(); router.push("/nutrition/add"); return; } if (key === "workout") { close(); router.push("/plan"); return; } setActive(key); }} className="flex min-h-32 flex-col items-center justify-center gap-3 rounded-2xl border border-slate-200 bg-white transition hover:border-blue-300 hover:bg-blue-50 active:scale-[.98]"><span className={`flex h-12 w-12 items-center justify-center rounded-full ${tone === "green" ? "bg-emerald-50 text-emerald-500" : tone === "purple" ? "bg-violet-50 text-violet-500" : tone === "orange" ? "bg-orange-50 text-orange-500" : "bg-blue-50 text-blue-600"}`}><Icon size={24} /></span><span className="font-semibold">{title}</span></button>)}</div> : active === "water" ? <WaterForm water={water} onSave={amount => run(async () => { await addWater(amount); })} /> : active === "expense" ? <ExpenseForm onSave={expense => run(async () => { await addExpense(expense); })} /> : active === "body" ? <BodyForm onSave={body => run(async () => { await addBody(body); })} /> : active === "work" ? <WorkForm onSave={input => run(async () => { await addWork({ date: currentRecordDate(), ...input }); })} /> : active === "cardio" ? <CardioForm onSave={input => run(async () => { await addCardio({ date: currentRecordDate(), ...input }); })} /> : <NoteForm onSave={text => run(async () => { await addNote(text); })} />}
  </Sheet>;
}

function WaterForm({ water, onSave }: { water: number; onSave: (amount: number) => Promise<void> }) { const [custom, setCustom] = useState(""); const customAmount = Number(custom); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">今天已喝</div><div className="mt-1 text-3xl font-bold text-blue-600">{water} <span className="text-sm font-medium text-slate-500">/ 2500 ml</span></div></div><div className="grid grid-cols-3 gap-3">{[200, 300, 500].map(amount => <button key={amount} onClick={() => void onSave(amount)} className="secondary-button px-2">+{amount} ml</button>)}</div><div className="mt-5 flex gap-3"><input className="field" type="number" min="1" placeholder="自定义 ml" value={custom} onChange={event => setCustom(event.target.value)} /><button disabled={!Number.isFinite(customAmount) || customAmount <= 0} className="primary-button" onClick={() => void onSave(customAmount)}>添加</button></div></div>; }

function ExpenseForm({ onSave }: { onSave: (expense: { amount: number; category: string; note: string }) => Promise<void> }) { const [amount, setAmount] = useState(""); const [category, setCategory] = useState("餐饮"); const [categories, setCategories] = useState(["餐饮", "交通", "购物", "娱乐", "健身", "学习", "其他"]); const [note, setNote] = useState(""); const numericAmount = Number(amount); useEffect(() => { void getExpenseCategories().then(items => { if (items.length) setCategories(items.map(item => item.name)); }).catch(() => undefined); }, []); return <div><label className="muted">金额</label><div className="mt-2 flex items-center gap-2"><span className="text-3xl font-bold">¥</span><input className="field text-2xl font-bold" type="number" min="0.01" step="0.01" placeholder="0.00" value={amount} onChange={event => setAmount(event.target.value)} /></div><div className="mt-5 grid grid-cols-4 gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-2 py-3 text-sm ${category === item ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item}</button>)}</div><input className="field mt-5" placeholder="备注（可选）" value={note} onChange={event => setNote(event.target.value)} /><button disabled={!Number.isFinite(numericAmount) || numericAmount <= 0} className="primary-button mt-5 w-full" onClick={() => void onSave({ amount: numericAmount, category, note })}>保存支出</button></div>; }

function BodyForm({ onSave }: { onSave: (body: { weight: number; time: string }) => Promise<void> }) { const [weight, setWeight] = useState(""); const [time, setTime] = useState(() => new Intl.DateTimeFormat("zh-CN", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "Asia/Shanghai" }).format(new Date())); const numericWeight = Number(weight); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">晨重</div><div className="mt-1 flex items-baseline justify-center gap-2"><input className="w-36 bg-transparent text-center text-5xl font-bold text-blue-600 outline-none" type="number" min="1" step="0.1" placeholder="60.0" value={weight} onChange={event => setWeight(event.target.value)} /><span className="text-slate-500">kg</span></div></div><label className="muted">测量时间</label><input className="field mt-2" type="time" value={time} onChange={event => setTime(event.target.value)} /><button disabled={!Number.isFinite(numericWeight) || numericWeight <= 0} className="primary-button mt-5 w-full" onClick={() => void onSave({ weight: numericWeight, time })}>保存晨重</button></div>; }

function NoteForm({ onSave }: { onSave: (text: string) => Promise<void> }) { const [text, setText] = useState(""); return <div><label className="muted">今天想记下什么？</label><textarea className="field mt-2 min-h-32 resize-none" placeholder="写下此刻的想法、灵感或提醒" value={text} onChange={event => setText(event.target.value)} /><button className="primary-button mt-5 w-full" disabled={!text.trim()} onClick={() => void onSave(text)}>保存随手记</button></div>; }
function WorkForm({ onSave }: { onSave: (input: { sessionType: "work"; title: string; durationMinutes: number; didText?: string }) => Promise<void> }) { const [title, setTitle] = useState("专注工作"); const [duration, setDuration] = useState("90"); const [didText, setDidText] = useState(""); return <div><label className="muted">工作标题</label><input className="field mt-2" value={title} onChange={event => setTitle(event.target.value)} /><label className="muted mt-4 block">时长（分钟）</label><input className="field mt-2" type="number" min="0" value={duration} onChange={event => setDuration(event.target.value)} /><textarea className="field mt-4 min-h-24 resize-none" placeholder="完成了什么？" value={didText} onChange={event => setDidText(event.target.value)} /><button className="primary-button mt-5 w-full" onClick={() => void onSave({ sessionType: "work", title, durationMinutes: Number(duration) || 0, didText })}>保存工作记录</button></div>; }
function CardioForm({ onSave }: { onSave: (input: { cardioType: string; durationMinutes: number }) => Promise<void> }) { const [cardioType, setCardioType] = useState("爬坡走"); const [duration, setDuration] = useState("20"); return <div><label className="muted">有氧类型</label><input className="field mt-2" value={cardioType} onChange={event => setCardioType(event.target.value)} /><label className="muted mt-4 block">时长（分钟）</label><input className="field mt-2" type="number" min="1" value={duration} onChange={event => setDuration(event.target.value)} /><button className="primary-button mt-5 w-full" onClick={() => void onSave({ cardioType, durationMinutes: Number(duration) || 1 })}>保存有氧</button></div>; }
