"use client";

import { Activity, BriefcaseBusiness, Camera, Dumbbell, Droplets, NotebookPen, Scale, Utensils, Wallet } from "lucide-react";
import { useEffect, useState } from "react";
import { useAppState } from "@/components/app-state";
import { getExpenseCategories } from "@/services/backend-service";
import { Sheet } from "@/components/ui";

type ActionKey = "water" | "expense" | "body" | "note";
const actions = [{ key: "meal", title: "饮食", icon: Utensils, tone: "green" }, { key: "water", title: "饮水", icon: Droplets, tone: "blue" }, { key: "workout", title: "训练", icon: Dumbbell, tone: "purple" }, { key: "expense", title: "支出", icon: Wallet, tone: "orange" }, { key: "body", title: "体重", icon: Scale, tone: "blue" }, { key: "work", title: "工作", icon: BriefcaseBusiness, tone: "green" }, { key: "cardio", title: "有氧", icon: Activity, tone: "green" }, { key: "note", title: "随手记", icon: NotebookPen, tone: "purple" }, { key: "photo", title: "图片", icon: Camera, tone: "orange" }] as const;

export function QuickAddSheet({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [active, setActive] = useState<ActionKey | null>(null);
  const [error, setError] = useState("");
  const { water, addWater, addExpense, addBody, addNote } = useAppState();
  const close = () => { setActive(null); setError(""); onClose(); };
  const run = async (operation: () => Promise<void>) => { try { setError(""); await operation(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败，请重试"); } };
  return <Sheet open={open} title={active ? ({ water: "记录饮水", expense: "记录支出", body: "记录晨重", note: "随手记" }[active]) : "快速记录"} subtitle={active ? "默认记录到今天" : "选择要记录的类型，快速添加"} onClose={close}>
    {error && <p className="mb-4 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>}
    {active === null ? <div className="grid grid-cols-3 gap-3">{actions.map(({ key, title, icon: Icon, tone }) => <button key={key} onClick={() => { if (key === "meal") { window.location.href = "/nutrition/add"; return; } if (key === "workout") { window.location.href = "/workout/push-2026-08-17"; return; } if (key === "photo") { window.location.href = "/history"; return; } if (key === "work" || key === "cardio") { close(); return; } if (key === "water" || key === "expense" || key === "body" || key === "note") setActive(key); }} className="flex aspect-square flex-col items-center justify-center gap-3 rounded-2xl border border-slate-200 bg-white transition hover:border-blue-300 hover:bg-blue-50"><span className={`flex h-12 w-12 items-center justify-center rounded-full ${tone === "green" ? "bg-emerald-50 text-emerald-500" : tone === "purple" ? "bg-violet-50 text-violet-500" : tone === "orange" ? "bg-orange-50 text-orange-500" : "bg-blue-50 text-blue-600"}`}><Icon size={24} /></span><span className="font-semibold">{title}</span></button>)}</div> : active === "water" ? <WaterForm water={water} onSave={amount => run(async () => { await addWater(amount); })} /> : active === "expense" ? <ExpenseForm onSave={expense => run(async () => { await addExpense(expense); })} /> : active === "body" ? <BodyForm onSave={body => run(async () => { await addBody(body); })} /> : <NoteForm onSave={text => run(async () => { await addNote(text); })} />}
  </Sheet>;
}

function WaterForm({ water, onSave }: { water: number; onSave: (amount: number) => Promise<void> }) { const [custom, setCustom] = useState(""); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">今天已喝</div><div className="mt-1 text-3xl font-bold text-blue-600">{water} <span className="text-sm font-medium text-slate-500">/ 2500 ml</span></div></div><div className="grid grid-cols-3 gap-3">{[200, 300, 500].map(amount => <button key={amount} onClick={() => void onSave(amount)} className="secondary-button px-2">+{amount} ml</button>)}</div><div className="mt-5 flex gap-3"><input className="field" type="number" placeholder="自定义 ml" value={custom} onChange={event => setCustom(event.target.value)} /><button className="primary-button" onClick={() => void onSave(Number(custom) || 300)}>添加</button></div></div>; }

function ExpenseForm({ onSave }: { onSave: (expense: { amount: number; category: string; note: string }) => Promise<void> }) { const [amount, setAmount] = useState("28"); const [category, setCategory] = useState("餐饮"); const [categories, setCategories] = useState(["餐饮", "交通", "购物", "娱乐", "健身", "学习", "其他"]); const [note, setNote] = useState(""); useEffect(() => { void getExpenseCategories().then(items => { if (items.length) setCategories(items.map(item => item.name)); }).catch(() => undefined); }, []); return <div><label className="muted">金额</label><div className="mt-2 flex items-center gap-2"><span className="text-3xl font-bold">¥</span><input className="field text-2xl font-bold" value={amount} onChange={event => setAmount(event.target.value)} /></div><div className="mt-5 grid grid-cols-4 gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-2 py-3 text-sm ${category === item ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item}</button>)}</div><input className="field mt-5" placeholder="备注（可选）" value={note} onChange={event => setNote(event.target.value)} /><button className="primary-button mt-5 w-full" onClick={() => void onSave({ amount: Number(amount) || 0, category, note })}>保存 ¥{amount || 0}</button></div>; }

function BodyForm({ onSave }: { onSave: (body: { weight: number; time: string }) => Promise<void> }) { const [weight, setWeight] = useState("60.0"); return <div><div className="app-card mb-5 bg-blue-50/60 p-5 text-center"><div className="text-sm text-slate-500">晨重</div><div className="mt-1 flex items-baseline justify-center gap-2"><input className="w-36 bg-transparent text-center text-5xl font-bold text-blue-600 outline-none" value={weight} onChange={event => setWeight(event.target.value)} /><span className="text-slate-500">kg</span></div></div><label className="muted">测量时间</label><input className="field mt-2" type="time" defaultValue="07:05" /><button className="primary-button mt-5 w-full" onClick={() => void onSave({ weight: Number(weight) || 0, time: "07:05" })}>保存晨重</button></div>; }

function NoteForm({ onSave }: { onSave: (text: string) => Promise<void> }) { const [text, setText] = useState(""); return <div><label className="muted">今天想记下什么？</label><textarea className="field mt-2 min-h-32 resize-none" placeholder="写下此刻的想法、灵感或提醒" value={text} onChange={event => setText(event.target.value)} /><button className="primary-button mt-5 w-full" disabled={!text.trim()} onClick={() => void onSave(text)}>保存随手记</button></div>; }
