"use client";

import Link from "next/link";
import { Check, Cloud, Download, Heart, LockKeyhole, Plus, ShieldCheck, Target, Trash2, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { currentRecordDate } from "@/services/backend-service";
import { createFood, createMealTemplate, createNutritionGoal, deactivateFood, getFoods, getMealTemplates, getNutritionGoals, updateFood } from "@/services/nutrition-service";
import { BackLink, Badge, SectionHeader } from "@/components/ui";
import { PwaInstallButton } from "@/components/pwa-install-button";
import { FoodLibraryPanel } from "@/components/food-library-section";
import { MealTemplatesPanel } from "@/components/meal-templates-section";
import type { FoodLibraryItem, MealTemplateRecord, NutritionGoalRecord } from "@/types";

const copy: Record<string, { title: string; subtitle: string; icon: typeof UserRound }> = { profile: { title: "个人资料", subtitle: "让每日目标更贴近真实的你。", icon: UserRound }, goals: { title: "每日目标", subtitle: "目标可以随阶段调整，历史记录保持不变。", icon: Target }, foods: { title: "食品库", subtitle: "管理常用食品和营养快照。", icon: Plus }, "meal-templates": { title: "餐食模板", subtitle: "把高频餐食变成一键记录。", icon: Plus }, training: { title: "训练计划", subtitle: "推拉腿 + 核心 V1，只影响未来训练。", icon: Target }, security: { title: "PIN 与安全", subtitle: "服务端 Session 已启用。", icon: LockKeyhole }, export: { title: "数据导出", subtitle: "后续支持完整 JSON / CSV 导出。", icon: Download }, sync: { title: "同步状态", subtitle: "当前记录通过 服务接口 持久化。", icon: Cloud }, app: { title: "应用设置", subtitle: "安装到主屏幕，像应用一样使用。", icon: ShieldCheck } };

export default function MeSectionPage() { const { section } = useParams<{ section: string }>(); if (section === "foods") return <SettingsFrame title="食品库" subtitle="管理常用食品和营养快照。" icon={Plus}><FoodLibraryPanel /></SettingsFrame>; if (section === "meal-templates") return <SettingsFrame title="餐食模板" subtitle="把高频餐食变成一键记录。" icon={Plus}><MealTemplatesPanel /></SettingsFrame>; if (section === "goals") return <NutritionGoalsSection />; if (section === "app") return <PwaSettingsSection />; const config = copy[section] ?? copy.profile; const Icon = config.icon; return <SettingsFrame title={config.title} subtitle={config.subtitle} icon={Icon}><div className="app-card mt-6 flex items-center gap-4 bg-blue-50/60 p-5"><div className="icon-tile h-14 w-14 bg-white text-blue-600"><Icon size={26} /></div><div><Badge tone="blue">服务已就绪</Badge><div className="mt-2 font-semibold">这一页已准备好真实数据接口</div><div className="mt-1 text-sm text-slate-500">当前阶段只接入 饮食数据。</div></div></div><div className="app-card mt-4 p-5"><SectionHeader title="当前配置" /><div className="space-y-3">{["显示名称 · 个人每日系统", "时区 · Asia/Shanghai", "目标 · 体态重组", "状态 · 服务接口已连接"].map(item => <div key={item} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">{item.split(" · ")[0]}</span><span className="font-semibold">{item.split(" · ")[1]}</span></div>)}</div></div></SettingsFrame>; }

function PwaSettingsSection() { return <SettingsFrame title="应用设置" subtitle="安装到主屏幕，像应用一样使用。" icon={ShieldCheck}><div className="app-card mt-6 p-5"><SectionHeader title="安装到手机" /><p className="mb-4 text-sm leading-6 text-slate-500">安装后可以从手机桌面直接打开 Powerlog，使用体验更接近原生应用。</p><PwaInstallButton /></div><div className="app-card mt-4 flex items-center gap-4 bg-blue-50/60 p-5"><div className="icon-tile h-14 w-14 bg-white text-blue-600"><ShieldCheck size={26} /></div><div><Badge tone="blue">服务已就绪</Badge><div className="mt-2 font-semibold">这一页已准备好真实数据接口</div><div className="mt-1 text-sm text-slate-500">当前阶段只接入 饮食数据。</div></div></div><div className="app-card mt-4 p-5"><SectionHeader title="当前配置" /><div className="space-y-3">{["显示名称 · 个人每日系统", "时区 · Asia/Shanghai", "目标 · 体态重组", "状态 · 服务接口已连接"].map(item => <div key={item} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 text-sm"><span className="text-slate-500">{item.split(" · ")[0]}</span><span className="font-semibold">{item.split(" · ")[1]}</span></div>)}</div></div></SettingsFrame>; }

function SettingsFrame({ title, subtitle, icon: Icon, children }: { title: string; subtitle: string; icon: typeof UserRound; children: React.ReactNode }) { return <><div className="flex items-center gap-2 pt-4 md:pt-8"><BackLink href="/me" /><div className="icon-tile h-10 w-10 bg-blue-50 text-blue-600"><Icon size={19} /></div><div><h1 className="sr-only">{title}</h1><div className="eyebrow">设置 · {title}</div></div></div><p className="mt-2 pl-10 text-slate-500">{subtitle}</p>{children}</>; }

function FoodLibrarySection() {
  const [foods, setFoods] = useState<FoodLibraryItem[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [name, setName] = useState(""); const [brand, setBrand] = useState(""); const [servingWeightG, setServingWeightG] = useState("100"); const [calories, setCalories] = useState("0"); const [protein, setProtein] = useState("0"); const [carbs, setCarbs] = useState("0"); const [fat, setFat] = useState("0"); const [fiber, setFiber] = useState("0");
  const load = async () => { try { setFoods(await getFoods(search, true)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "食品库暂时不可用"); } }; useEffect(() => { void getFoods(search, true).then(setFoods).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "食品库暂时不可用")); }, [search]);
  const save = async () => { try { await createFood({ name, brand: brand || null, servingName: `${servingWeightG}g`, servingWeightG: Number(servingWeightG), weightBasis: "cooked", caloriesPer100G: Number(calories), proteinPer100G: Number(protein), carbsPer100G: Number(carbs), fatPer100G: Number(fat), fiberPer100G: Number(fiber) }); setName(""); setBrand(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "食品保存失败"); } };
  const toggleFavorite = async (food: FoodLibraryItem) => { await updateFood(food.id, { isFavorite: !food.isFavorite }); await load(); }; const deactivate = async (food: FoodLibraryItem) => { await deactivateFood(food.id); await load(); };
  return <SettingsFrame title="食品库" subtitle="管理常用食品和营养快照。" icon={Plus}>{error && <ErrorBox text={error} />}<div className="app-card mt-6 p-5"><SectionHeader title="新增食品" /><div className="grid gap-3 sm:grid-cols-2"><input className="field" placeholder="食品名称" value={name} onChange={event => setName(event.target.value)} /><input className="field" placeholder="品牌（可选）" value={brand} onChange={event => setBrand(event.target.value)} /><input className="field" type="number" placeholder="每份克数" value={servingWeightG} onChange={event => setServingWeightG(event.target.value)} /><input className="field" type="number" placeholder="热量 / 100克" value={calories} onChange={event => setCalories(event.target.value)} /><input className="field" type="number" placeholder="蛋白质 / 100克" value={protein} onChange={event => setProtein(event.target.value)} /><input className="field" type="number" placeholder="碳水 / 100克" value={carbs} onChange={event => setCarbs(event.target.value)} /><input className="field" type="number" placeholder="脂肪 / 100克" value={fat} onChange={event => setFat(event.target.value)} /><input className="field" type="number" placeholder="膳食纤维 / 100克" value={fiber} onChange={event => setFiber(event.target.value)} /></div><button disabled={!name.trim()} onClick={() => void save()} className="primary-button mt-4 w-full"><Plus size={18} />新增食品</button></div><div className="app-card mt-4 p-5"><SectionHeader title="食品库" /><input className="field" placeholder="搜索食品" value={search} onChange={event => setSearch(event.target.value)} /><div className="mt-3 divide-y divide-slate-100">{foods.map(food => <div key={food.id} className={`flex items-center gap-3 py-3 ${!food.isActive ? "opacity-50" : ""}`}><div className="min-w-0 flex-1"><div className="font-semibold">{food.name}</div><div className="text-xs text-slate-400">{food.brand ?? "无品牌"} · {food.caloriesPer100G} kcal · P {food.proteinPer100G}</div></div><button aria-label={`收藏${food.name}`} onClick={() => void toggleFavorite(food)} className="rounded-lg p-2"><Heart size={17} className={food.isFavorite ? "fill-orange-400 text-orange-400" : "text-slate-300"} /></button>{food.isActive && <button aria-label={`停用${food.name}`} onClick={() => void deactivate(food)} className="rounded-lg p-2 text-slate-400 hover:text-red-500"><Trash2 size={17} /></button>}</div>)}</div></div></SettingsFrame>;
}

function MealTemplatesSection() { const [foods, setFoods] = useState<FoodLibraryItem[]>([]); const [templates, setTemplates] = useState<MealTemplateRecord[]>([]); const [selected, setSelected] = useState<Record<string, number>>({}); const [name, setName] = useState("早餐 A"); const [error, setError] = useState(""); const load = async () => { try { setFoods(await getFoods()); setTemplates(await getMealTemplates()); } catch (reason) { setError(reason instanceof Error ? reason.message : "模板暂时不可用"); } }; useEffect(() => { void load(); }, []); const save = async () => { try { await createMealTemplate({ name, mealType: "breakfast", items: Object.entries(selected).map(([foodId, quantityG]) => ({ foodId, quantityG })) }); setSelected({}); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "模板保存失败"); } }; return <SettingsFrame title="餐食模板" subtitle="把高频餐食变成一键记录。" icon={Plus}>{error && <ErrorBox text={error} />}<div className="app-card mt-6 p-5"><SectionHeader title="创建模板" /><input className="field" value={name} onChange={event => setName(event.target.value)} placeholder="模板名称" /><div className="mt-3 divide-y divide-slate-100">{foods.map(food => <div key={food.id} className="flex items-center gap-3 py-3"><button onClick={() => setSelected(current => current[food.id] ? Object.fromEntries(Object.entries(current).filter(([id]) => id !== food.id)) : { ...current, [food.id]: food.servingWeightG ?? 100 })} className={`icon-tile h-9 w-9 ${selected[food.id] ? "bg-blue-600 text-white" : "bg-slate-50 text-slate-500"}`}><Check size={17} /></button><span className="flex-1 text-sm font-semibold">{food.name}</span>{selected[food.id] && <input className="field w-24 px-2" type="number" value={selected[food.id]} onChange={event => setSelected(current => ({ ...current, [food.id]: Number(event.target.value) || 1 }))} />}</div>)}</div><button disabled={!Object.keys(selected).length} onClick={() => void save()} className="primary-button mt-4 w-full"><Plus size={18} />保存模板</button></div><div className="app-card mt-4 p-5"><SectionHeader title="已有模板" />{templates.map(template => <div key={template.id} className="flex items-center justify-between border-b border-slate-100 py-3"><span className="font-semibold">{template.name}</span><Badge>{template.items.length} 项</Badge></div>)}</div></SettingsFrame>; }

 function NutritionGoalsSection() { const [goals, setGoals] = useState<NutritionGoalRecord[]>([]); const [error, setError] = useState(""); const [calories, setCalories] = useState("2050"); const [protein, setProtein] = useState("125"); const [carbs, setCarbs] = useState("270"); const [fat, setFat] = useState("55"); const [fiber, setFiber] = useState("28"); const [water, setWater] = useState("2500"); const load = async () => { try { setGoals(await getNutritionGoals()); } catch (reason) { setError(reason instanceof Error ? reason.message : "目标暂时不可用"); } }; useEffect(() => { void load(); }, []); const save = async () => { try { await createNutritionGoal({ effectiveFrom: currentRecordDate(), calories: Number(calories), protein: Number(protein), carbs: Number(carbs), fat: Number(fat), fiber: Number(fiber), water: Number(water), note: null }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "目标保存失败"); } }; return <SettingsFrame title="每日目标" subtitle="目标可以随阶段调整，历史记录保持不变。" icon={Target}>{error && <ErrorBox text={error} />}<div className="app-card mt-6 p-5"><SectionHeader title="新增目标版本" /><div className="grid grid-cols-2 gap-3"><input className="field" type="number" value={calories} onChange={event => setCalories(event.target.value)} placeholder="热量" /><input className="field" type="number" value={protein} onChange={event => setProtein(event.target.value)} placeholder="蛋白质" /><input className="field" type="number" value={carbs} onChange={event => setCarbs(event.target.value)} placeholder="碳水" /><input className="field" type="number" value={fat} onChange={event => setFat(event.target.value)} placeholder="脂肪" /><input className="field" type="number" value={fiber} onChange={event => setFiber(event.target.value)} placeholder="膳食纤维" /><input className="field" type="number" value={water} onChange={event => setWater(event.target.value)} placeholder="饮水（毫升）" /></div><button onClick={() => void save()} className="primary-button mt-4 w-full"><Check size={18} />保存目标版本</button></div><div className="app-card mt-4 p-5"><SectionHeader title="历史版本" />{goals.map(goal => <div key={goal.id} className="border-b border-slate-100 py-3 text-sm"><div className="font-semibold">{goal.effectiveFrom} 起</div><div className="mt-1 text-slate-500">{goal.calories} kcal · P {goal.protein} · C {goal.carbs} · F {goal.fat} · 水 {goal.water} ml</div></div>)}</div></SettingsFrame>; }

function ErrorBox({ text }: { text: string }) { return <div className="mt-4 rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-600">{text}</div>; }
