"use client";

import { BarChart3, CalendarDays, ChevronRight, Droplets, Dumbbell, Flame, Moon, Wallet } from "lucide-react";
import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { insightNutrition, insightWeight } from "@/mock/data";
import { PageIntro, ProgressBar, SectionHeader } from "@/components/ui";

const categories = [{ key: "body", label: "身体", icon: BarChart3 }, { key: "nutrition", label: "营养", icon: Flame }, { key: "training", label: "训练", icon: Dumbbell }, { key: "life", label: "生活", icon: Moon }, { key: "finance", label: "消费", icon: Wallet }];
export default function InsightsPage() { const [range, setRange] = useState("30天"); const [category, setCategory] = useState("body"); return <><PageIntro eyebrow="Trends over time" title="数据" subtitle="看趋势，比看某一天更重要。" action={<button className="secondary-button h-11 w-11 p-0"><CalendarDays size={20} /></button>} /><div className="app-card grid grid-cols-4 gap-1 p-1">{["7天", "30天", "3月", "1年"].map(item => <button key={item} onClick={() => setRange(item)} className={`rounded-2xl py-3 text-sm font-semibold ${range === item ? "bg-white text-blue-600 shadow-soft" : "text-slate-500"}`}>{item}</button>)}</div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{categories.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setCategory(key)} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold ${category === key ? "bg-blue-600 text-white shadow-md" : "bg-white text-slate-500"}`}><Icon size={18} />{label}</button>)}</div>{category === "body" && <BodyInsights range={range} />}{category === "nutrition" && <NutritionInsights range={range} />}{category === "training" && <TrainingInsights />}{category === "life" && <LifeInsights />}{category === "finance" && <FinanceInsights />}</> }
function BodyInsights({ range }: { range: string }) { return <><div className="mt-5 grid grid-cols-3 gap-3"><Stat title="当前" value="60.0" unit="kg" /><Stat title="30日变化" value="-0.3" unit="kg" tone="green" /><Stat title="7日平均" value="60.1" unit="kg" /></div><div className="app-card mt-4 p-5"><SectionHeader title="体重趋势" action={<span className="text-sm text-slate-400">过去 {range}</span>} /><div className="h-60"><ResponsiveContainer width="100%" height="100%"><AreaChart data={insightWeight} margin={{ left: -20, right: 4, top: 10, bottom: 0 }}><defs><linearGradient id="weightFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.2} /><stop offset="100%" stopColor="#2563eb" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={[59, 62]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14, boxShadow: "0 8px 30px rgba(15,23,42,.12)" }} /><Area type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={3} fill="url(#weightFill)" /></AreaChart></ResponsiveContainer></div></div><div className="app-card mt-4 p-5"><SectionHeader title="身体状态" /><div className="grid grid-cols-2 gap-3"><MetricLine label="腰围" value="73.5 cm" trend="-0.8 cm" /><MetricLine label="体脂率" value="15.8%" trend="-0.4%" /></div></div></> }
function NutritionInsights({ range }: { range: string }) { return <><div className="app-card mt-5 p-5"><SectionHeader title="营养平均值" action={<span className="text-sm text-slate-400">过去 {range}</span>} /><div className="grid grid-cols-3 divide-x divide-slate-100"><Stat title="平均热量" value="2067" unit="kcal" tone="orange" /><Stat title="蛋白质" value="121" unit="g" tone="green" /><Stat title="饮水" value="2280" unit="ml" /></div></div><div className="app-card mt-4 p-5"><SectionHeader title="热量趋势" /><div className="h-60"><ResponsiveContainer width="100%" height="100%"><LineChart data={insightNutrition} margin={{ left: -20, right: 4, top: 10 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} /><Line type="monotone" dataKey="value" stroke="#f59e0b" strokeWidth={3} dot={{ r: 3, fill: "#f59e0b" }} /></LineChart></ResponsiveContainer></div></div><div className="app-card mt-4 p-5"><SectionHeader title="营养目标达成" /><NutritionRow label="蛋白质" value="121 / 125g" percent={97} color="green" /><NutritionRow label="碳水" value="264 / 270g" percent={98} color="blue" /><NutritionRow label="膳食纤维" value="26 / 28g" percent={93} color="green" /></div></> }
function TrainingInsights() { return <><div className="mt-5 grid grid-cols-2 gap-3"><Stat title="过去 30 天" value="19" unit="次训练" tone="purple" /><Stat title="总时长" value="17h 42m" /></div><div className="app-card mt-4 p-5"><SectionHeader title="训练分布" /><div className="grid grid-cols-4 gap-2 text-center">{[["Push", 5, "bg-blue-500"], ["Pull", 5, "bg-violet-500"], ["Legs", 4, "bg-emerald-500"], ["Core", 5, "bg-orange-500"]].map(([name, value, color]) => <div key={String(name)}><div className="mx-auto flex h-20 w-4 items-end rounded-full bg-slate-100"><div className={`w-full rounded-full ${String(color)}`} style={{ height: `${Number(value) * 12}px` }} /></div><div className="mt-2 text-sm font-semibold">{name}</div><div className="text-xs text-slate-400">{value} 次</div></div>)}</div></div><div className="app-card mt-4 p-5"><SectionHeader title="动作进步" action={<button className="text-sm font-semibold text-blue-600">杠铃卧推 <ChevronRight className="inline" size={15} /></button>} /><div className="flex items-center justify-between rounded-2xl bg-blue-50 p-4"><div><div className="text-sm text-slate-500">最佳工作组</div><div className="mt-1 text-2xl font-bold text-blue-600">45kg × 8</div></div><BarChart3 className="text-blue-600" /></div></div></> }
function LifeInsights() { return <div className="mt-5 grid gap-3 sm:grid-cols-2"><LifeCard icon={<Moon />} title="睡眠" value="7h 13m" subtitle="平均时长" /><LifeCard icon={<Droplets />} title="饮水" value="2280ml" subtitle="平均每日" /><LifeCard icon={<BarChart3 />} title="工作 / 学习" value="6h 42m" subtitle="平均每日" /><LifeCard icon={<Dumbbell />} title="有氧" value="78min" subtitle="本周累计" /></div>; }
function FinanceInsights() { return <><div className="app-card mt-5 p-5"><div className="text-sm text-slate-500">8 月支出</div><div className="mt-1 text-4xl font-bold text-orange-500">¥1,842</div><div className="mt-5"><ProgressBar value={64} color="orange" /></div></div><div className="app-card mt-4 divide-y divide-slate-100 p-5"><SectionHeader title="分类汇总" />{[["餐饮", "¥921", 50], ["交通", "¥320", 18], ["健身", "¥280", 15], ["其他", "¥321", 17]].map(([label, value, percent]) => <div key={String(label)} className="py-3"><div className="flex justify-between text-sm"><span>{label}</span><span className="font-semibold">{value}</span></div><div className="mt-2"><ProgressBar value={Number(percent)} color="orange" /></div></div>)}</div></> }
function Stat({ title, value, unit, tone = "blue" }: { title: string; value: string; unit?: string; tone?: "blue" | "green" | "orange" | "purple" }) { const colors = { blue: "text-blue-600", green: "text-emerald-500", orange: "text-orange-500", purple: "text-violet-600" }; return <div className="app-card p-4"><div className="text-xs text-slate-500">{title}</div><div className={`mt-2 text-xl font-bold ${colors[tone]}`}>{value}</div>{unit && <div className="mt-1 text-xs text-slate-400">{unit}</div>}</div>; }
function MetricLine({ label, value, trend }: { label: string; value: string; trend: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 font-bold">{value}</div><div className="mt-1 text-xs font-semibold text-emerald-500">{trend}</div></div>; }
function NutritionRow({ label, value, percent, color }: { label: string; value: string; percent: number; color: "blue" | "green" }) { return <div className="mb-4 last:mb-0"><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="font-semibold text-slate-600">{value}</span></div><ProgressBar value={percent} color={color} /></div>; }
function LifeCard({ icon, title, value, subtitle }: { icon: React.ReactNode; title: string; value: string; subtitle: string }) { return <div className="app-card flex items-center gap-4 p-5"><div className="icon-tile bg-blue-50 text-blue-600">{icon}</div><div><div className="font-semibold">{title}</div><div className="mt-1 text-2xl font-bold text-blue-600">{value}</div><div className="text-xs text-slate-400">{subtitle}</div></div></div>; }
