"use client";

import { BarChart3, CalendarDays, Droplets, Dumbbell, Flame, Moon, Wallet } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EmptyState, PageIntro, ProgressBar, SectionHeader } from "@/components/ui";
import { getInsightsData } from "@/services/backend-service";
import type { InsightCategory, InsightRange, InsightSeriesPoint, InsightsPayload } from "@/types/insights";

const ranges: Array<{ key: InsightRange; label: string }> = [{ key: "7d", label: "7天" }, { key: "30d", label: "30天" }, { key: "3m", label: "3月" }, { key: "1y", label: "1年" }];
const categories: Array<{ key: InsightCategory; label: string; icon: typeof BarChart3 }> = [
  { key: "body", label: "身体", icon: BarChart3 }, { key: "nutrition", label: "营养", icon: Flame }, { key: "training", label: "训练", icon: Dumbbell }, { key: "life", label: "生活", icon: Moon }, { key: "finance", label: "消费", icon: Wallet },
];

function display(value: number | null | undefined, digits = 1): string { return value === null || value === undefined || !Number.isFinite(value) ? "—" : value.toFixed(digits); }
function whole(value: number | null | undefined): string { return display(value, 0); }
function duration(value: number | null | undefined): string { if (value === null || value === undefined || !Number.isFinite(value)) return "—"; const minutes = Math.round(value); const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `${hours} 小时 ${String(rest).padStart(2, "0")} 分钟` : `${rest} 分钟`; }
function rangeText(range: InsightRange): string { return ranges.find(item => item.key === range)?.label ?? "当前周期"; }
function hasPoint(points: InsightSeriesPoint[]): boolean { return points.some(point => point.value !== null); }

export default function InsightsPage() {
  const [range, setRange] = useState<InsightRange>("30d");
  const [category, setCategory] = useState<InsightCategory>("body");
  const [payload, setPayload] = useState<InsightsPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setLoading(true); setError(null); getInsightsData(range, category).then(result => { if (active) setPayload(result); }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : "数据暂时无法加载"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [range, category]);
  return <>
    <PageIntro eyebrow="趋势分析" title="数据" subtitle="看趋势，比看某一天更重要。" action={<button className="secondary-button h-11 w-11 p-0" aria-label="选择日期"><CalendarDays size={20} /></button>} />
    <div className="app-card grid grid-cols-4 gap-1 p-1">{ranges.map(item => <button key={item.key} onClick={() => setRange(item.key)} className={`rounded-2xl py-3 text-sm font-semibold ${range === item.key ? "bg-white text-blue-600 shadow-soft" : "text-slate-500"}`}>{item.label}</button>)}</div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{categories.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setCategory(key)} className={`flex shrink-0 items-center gap-2 rounded-2xl px-4 py-3 text-sm font-semibold ${category === key ? "bg-blue-600 text-white shadow-md" : "bg-white text-slate-500"}`}><Icon size={18} />{label}</button>)}</div>
    {loading && <div className="app-card mt-5 p-8 text-center text-sm text-slate-500">正在读取真实数据…</div>}
    {!loading && error && <EmptyState title="数据加载失败" description={error} />}
    {!loading && !error && category === "body" && payload?.body && <BodyInsights data={payload.body} range={range} />}
    {!loading && !error && category === "nutrition" && payload?.nutrition && <NutritionInsights data={payload.nutrition} range={range} />}
    {!loading && !error && category === "training" && payload?.training && <TrainingInsights data={payload.training} range={range} />}
    {!loading && !error && category === "life" && payload?.life && <LifeInsights data={payload.life} />}
    {!loading && !error && category === "finance" && payload?.finance && <FinanceInsights data={payload.finance} range={range} />}
  </>;
}

function BodyInsights({ data, range }: { data: NonNullable<InsightsPayload["body"]>; range: InsightRange }) {
  const hasWeight = hasPoint(data.weightTrend); const hasWaist = hasPoint(data.waistTrend);
  return <><div className="mt-5 grid grid-cols-3 gap-3"><Stat title="当前" value={display(data.currentWeightKg)} unit="kg" /><Stat title={`${rangeText(range)}变化`} value={display(data.periodChangeKg)} unit="kg" tone="green" /><Stat title="7日平均" value={display(data.averageWeight7dKg)} unit="kg" /></div>
    {!hasWeight && !hasWaist ? <EmptyState title="还没有身体数据" description="记录一次体重或腰围后，这里会开始显示趋势。" /> : <>{hasWeight && <ChartCard title="体重趋势" subtitle={`过去 ${rangeText(range)}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.weightTrend} margin={{ left: -20, right: 4, top: 10, bottom: 0 }}><defs><linearGradient id="weightFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.2} /><stop offset="100%" stopColor="#2563eb" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={["auto", "auto"]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} /><Area type="monotone" dataKey="value" name="体重" connectNulls={false} stroke="#2563eb" strokeWidth={3} fill="url(#weightFill)" /></AreaChart></ResponsiveContainer></ChartCard>}{hasWaist && <ChartCard title="腰围趋势" subtitle="只连接实际记录"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.waistTrend} margin={{ left: -20, right: 4, top: 10, bottom: 0 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={["auto", "auto"]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} /><Line type="monotone" dataKey="value" name="腰围" connectNulls={false} stroke="#8b5cf6" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></ChartCard>}</>}
    <div className="app-card mt-4 p-5"><SectionHeader title="身体状态" /><div className="grid grid-cols-2 gap-3"><MetricLine label="腰围" value={`${display(data.latestWaistCm)} cm`} trend={data.latestWaistCm === null ? "暂无记录" : "最近一次记录"} /><MetricLine label="体脂率" value={`${display(data.latestBodyFatPct)}%`} trend={data.latestBodyFatPct === null ? "暂无记录" : "最近一次记录"} /></div></div></>;
}

function NutritionInsights({ data, range }: { data: NonNullable<InsightsPayload["nutrition"]>; range: InsightRange }) {
  const rows = [{ label: "蛋白质", key: "protein" as const, unit: "g", color: "green" as const }, { label: "碳水", key: "carbs" as const, unit: "g", color: "blue" as const }, { label: "脂肪", key: "fat" as const, unit: "g", color: "orange" as const }, { label: "膳食纤维", key: "fiber" as const, unit: "g", color: "green" as const }];
  return <><div className="app-card mt-5 p-5"><SectionHeader title="营养平均值" action={<span className="text-sm text-slate-400">过去 {rangeText(range)}</span>} /><div className="grid grid-cols-3 divide-x divide-slate-100"><Stat title="平均热量" value={whole(data.averages.calories)} unit="kcal" tone="orange" /><Stat title="蛋白质" value={whole(data.averages.protein)} unit="g" tone="green" /><Stat title="饮水" value={whole(data.averageWaterMl)} unit="ml" /></div></div>{hasPoint(data.calorieTrend) ? <ChartCard title="热量趋势"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.calorieTrend} margin={{ left: -20, right: 4, top: 10 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={["auto", "auto"]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} /><Line type="monotone" dataKey="value" name="热量" connectNulls={false} stroke="#f59e0b" strokeWidth={3} dot={{ r: 3, fill: "#f59e0b" }} /></LineChart></ResponsiveContainer></ChartCard> : <EmptyState title="还没有饮食数据" description="添加餐食后，这里会显示真实的每日营养趋势。" />}<div className="app-card mt-4 p-5"><SectionHeader title="营养目标达成" />{rows.map(row => <NutritionRow key={row.key} label={row.label} value={`${whole(data.averages[row.key])} / ${whole(data.goals[row.key])}${row.unit}`} percent={data.achievementRates[row.key]} color={row.color} />)}</div></>;
}

function TrainingInsights({ data, range }: { data: NonNullable<InsightsPayload["training"]>; range: InsightRange }) {
  const [selectedKey, setSelectedKey] = useState(""); const selected = useMemo(() => data.exerciseTrends.find(item => `${item.exerciseId ?? ""}:${item.name}` === selectedKey) ?? data.exerciseTrends[0], [data.exerciseTrends, selectedKey]);
  useEffect(() => { if (!selected && data.exerciseTrends[0]) setSelectedKey(`${data.exerciseTrends[0].exerciseId ?? ""}:${data.exerciseTrends[0].name}`); }, [data.exerciseTrends, selected]);
  return <><div className="mt-5 grid grid-cols-2 gap-3"><Stat title={`过去 ${rangeText(range)}`} value={String(data.sessionsCount)} unit="次训练" tone="purple" /><Stat title="总时长" value={duration(data.totalDurationMinutes)} /></div><div className="mt-3 grid grid-cols-2 gap-3"><Stat title="工作组数" value={String(data.workingSets)} unit="组" tone="blue" /><Stat title="总训练量" value={`${display(data.totalVolumeKg)} kg`} tone="orange" /></div><div className="app-card mt-4 p-5"><SectionHeader title="训练分布" /><div className="grid grid-cols-4 gap-2 text-center">{([["推", data.splitCounts.push, "bg-blue-500"], ["拉", data.splitCounts.pull, "bg-violet-500"], ["腿", data.splitCounts.legs, "bg-emerald-500"], ["核心", data.splitCounts.core, "bg-orange-500"]] as const).map(([name, value, color]) => <div key={name}><div className="mx-auto flex h-20 w-4 items-end rounded-full bg-slate-100"><div className={`w-full rounded-full ${color}`} style={{ height: `${Math.min(80, Math.max(4, value * 12))}px` }} /></div><div className="mt-2 text-sm font-semibold">{name}</div><div className="text-xs text-slate-400">{value} 次</div></div>)}</div></div>{selected && hasPoint(selected.points) ? <ChartCard title="动作最佳工作重量" subtitle="仅统计 已完成的工作组" action={<select aria-label="选择动作" className="max-w-[150px] rounded-xl border-0 bg-blue-50 px-2 py-2 text-sm font-semibold text-blue-600" value={`${selected.exerciseId ?? ""}:${selected.name}`} onChange={event => setSelectedKey(event.target.value)}>{data.exerciseTrends.map(item => <option key={`${item.exerciseId ?? ""}:${item.name}`} value={`${item.exerciseId ?? ""}:${item.name}`}>{item.name}</option>)}</select>}><ResponsiveContainer width="100%" height="100%"><LineChart data={selected.points} margin={{ left: -20, right: 4, top: 10 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={["auto", "auto"]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} /><Line type="monotone" dataKey="value" name="kg" connectNulls={false} stroke="#2563eb" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></ChartCard> : <EmptyState title="还没有动作趋势" description="完成一次包含工作组的训练后，这里会显示最佳重量趋势。" />}</>;
}

function LifeInsights({ data }: { data: NonNullable<InsightsPayload["life"]> }) { return <div className="mt-5 grid gap-3 sm:grid-cols-2"><LifeCard icon={<Moon />} title="睡眠" value={duration(data.averageSleepMinutes)} subtitle={`平均时长 · 质量 ${display(data.averageSleepQuality)}/5`} /><LifeCard icon={<Droplets />} title="饮水" value={`${whole(data.averageWaterMl)} ml`} subtitle="有记录日平均" /><LifeCard icon={<BarChart3 />} title="工作 / 学习" value={duration(data.averageWorkMinutes)} subtitle={`日均 · 总计 ${duration(data.totalWorkMinutes)}`} /><LifeCard icon={<Dumbbell />} title="有氧" value={`${whole(data.totalCardioMinutes)} 分钟`} subtitle="周期累计" /></div>; }
function FinanceInsights({ data, range }: { data: NonNullable<InsightsPayload["finance"]>; range: InsightRange }) { return <><div className="app-card mt-5 p-5"><div className="text-sm text-slate-500">{rangeText(range)}支出</div><div className="mt-1 text-4xl font-bold text-orange-500">¥{data.totalAmount.toFixed(2)}</div><div className="mt-2 text-sm text-slate-500">日均 ¥{display(data.averageDailyAmount, 2)}</div></div>{hasPoint(data.dailyTrend) ? <ChartCard title="每日支出趋势"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.dailyTrend} margin={{ left: -20, right: 4, top: 10 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis domain={["auto", "auto"]} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ border: "0", borderRadius: 14 }} formatter={(value: number) => [`¥${value.toFixed(2)}`, "支出"]} /><Line type="monotone" dataKey="value" name="支出" connectNulls={false} stroke="#f97316" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></ChartCard> : <EmptyState title="还没有支出数据" description="添加一笔支出后，这里会显示真实趋势。" />}<div className="app-card mt-4 divide-y divide-slate-100 p-5"><SectionHeader title="分类汇总" />{data.categories.length ? data.categories.map(item => <div key={item.categoryId ?? "uncategorized"} className="py-3"><div className="flex justify-between text-sm"><span>{item.label}</span><span className="font-semibold">¥{item.amount.toFixed(2)}</span></div><div className="mt-2"><ProgressBar value={item.percent} color="orange" /></div></div>) : <div className="py-6 text-center text-sm text-slate-500">当前周期没有分类数据</div>}</div></>; }

function ChartCard({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: React.ReactNode; children: React.ReactNode }) { return <div className="app-card mt-4 p-5"><SectionHeader title={title} action={action ?? (subtitle ? <span className="text-sm text-slate-400">{subtitle}</span> : undefined)} /><div className="h-60">{children}</div></div>; }
function Stat({ title, value, unit, tone = "blue" }: { title: string; value: string; unit?: string; tone?: "blue" | "green" | "orange" | "purple" }) { const colors = { blue: "text-blue-600", green: "text-emerald-500", orange: "text-orange-500", purple: "text-violet-600" }; return <div className="app-card p-4"><div className="text-xs text-slate-500">{title}</div><div className={`mt-2 text-xl font-bold ${colors[tone]}`}>{value}</div>{unit && <div className="mt-1 text-xs text-slate-400">{unit}</div>}</div>; }
function MetricLine({ label, value, trend }: { label: string; value: string; trend: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 font-bold">{value}</div><div className="mt-1 text-xs font-semibold text-slate-400">{trend}</div></div>; }
function NutritionRow({ label, value, percent, color }: { label: string; value: string; percent: number | null; color: "blue" | "green" | "orange" }) { return <div className="mb-4 last:mb-0"><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="font-semibold text-slate-600">{value}</span></div><ProgressBar value={percent ?? 0} color={color} /></div>; }
function LifeCard({ icon, title, value, subtitle }: { icon: React.ReactNode; title: string; value: string; subtitle: string }) { return <div className="app-card flex items-center gap-4 p-5"><div className="icon-tile bg-blue-50 text-blue-600">{icon}</div><div><div className="font-semibold">{title}</div><div className="mt-1 text-2xl font-bold text-blue-600">{value}</div><div className="text-xs text-slate-400">{subtitle}</div></div></div>; }
